export const SET_INITIAL_TODOS: 'SET_INITIAL_TODOS' = 'SET_INITIAL_TODOS';
export const ADD_TODO: 'ADD_TODO' = 'ADD_TODO';
export const DELETE_TODO: 'DELETE_TODO' = 'DELETE_TODO';
export const CHANGE_TODO_STATUS: 'CHANGE_TODO_STATUS' = 'CHANGE_TODO_STATUS';